### PR TITLE
Enabled Hw Keys Overlay

### PR DESCRIPTION
**Pull request by vbajs**
hopefully this enables Hw keys settings for jfltexx

### CODE REVIEW

**Comment by akhilnarang** [comment]
Don't think we have hw keys settings
Right @srisurya95?

**Comment by vbajs** [comment]
Lol @ahilnarang , @srisurya95 is sleeping and you guys didn't add HW keys settings??

**Comment by vbajs** [comment]
Ok turns out you guys didn't so @minidude2012 DO NOT MERGE UNTIL IT'S ADDED!!

**Comment by srisurya95** [comment]
we don't have em

**Comment by vbajs** [comment]
Ok
So when you guys are gonna add it because not just jfltexx that needs this commit but also bacon

**Comment by akhilnarang** [comment]
Live without hw keys B)

**Comment by vbajs** [comment]
:-(

**Comment by vbajs** [comment]
Closing since you guys aren't gonna add HW keys settings

**Comment by srisurya95** [comment]
may add soon

**Comment by vbajs** [comment]
And i may reopen this pull request once its added

**Pull request closed without merging**
